### PR TITLE
fix: improve flow of typing in phrase, closes #526

### LINKED ISSUE #526: Improve Secret Key validation during entry
Hi  Please Help.
   I just downloaded the latest wallet version.
When I try to use my existing wallet 24 word key, it errors at word 12.   I know the key is correct works fine on wallet 3.1.1.
How do I restore my wallet on the new one.    It appears to be looking for a 12 word key... 
ERROR MESSAGE:
It appears you've entered a Secret Key originally created elsewhere than the Stacks Wallet. We recommend you create a new Secret Key with the Stacks Wallet for greater security.

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/494308376)

### CODE REVIEW

File: app/pages/onboarding/07-set-password/set-password.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ const weakPasswordWarningMessage = (result: ValidatedPassword) => {
 };
 
 export const SetPassword: React.FC = () => {
-  useBackButton(routes.VERIFY_KEY);
+  // useBackButton(routes.VERIFY_KEY);
```
Comment (kyranjamie) [inline app/pages/onboarding/07-set-password/set-password.tsx:41]: This need to be fixed, as if you restore you don't go back here.

File: app/pages/onboarding/03-restore-wallet/restore-wallet.tsx [hunk 2]
```diff
@@ -23,18 +23,22 @@ export const RestoreWallet: React.FC = () => {
...
 
   const [mnemonic, setMnemonic] = useState('');
+  const [hasSubmitted, setHasSubmitted] = useState(false);
   const [error, setError] = useState<string | null>(null);
   const history = useHistory();
   const dispatch = useDispatch();
 
   const handleMnemonicInput = (e: React.FormEvent<HTMLInputElement>) => {
+    setHasSubmitted(false);
+    setError(null);
```
Comment (aulneau) [inline app/pages/onboarding/03-restore-wallet/restore-wallet.tsx:33]: I think we should check these and only set them if they are not the values we are setting. Ideally we'd prob want to debounce this setMnemonic fn, too.

File: app/pages/onboarding/03-restore-wallet/restore-wallet.tsx [hunk 3]
```diff
@@ -88,7 +91,7 @@ export const RestoreWallet: React.FC = () => {
           <ErrorText>{error}</ErrorText>
         </ErrorLabel>
       )}
-      {mnemonicLength === 12 && (
+      {mnemonicLength === 12 && hasSubmitted && (
```
Comment (aulneau) [inline app/pages/onboarding/03-restore-wallet/restore-wallet.tsx:94]: I think a better pattern would be to check for an error, rather than if it's of a specific length

Comment (kyranjamie) [reply app/pages/onboarding/03-restore-wallet/restore-wallet.tsx:94]: This isn't an error, though. It's just showing a warning.

Comment (aulneau) [reply app/pages/onboarding/03-restore-wallet/restore-wallet.tsx:94]: ah, ok then!

**Review by zone117x — APPROVED** [review]
