### PR TITLE
fix: add more grave description about losing key, closes #275

### LINKED ISSUE #275: Edit description with more information about Secret Keys during registration
Per @ryanarndtcm's suggestion [here](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES?node-id=772:21524#42941165), making use of the provided copy suggestions and content found in the current web-based FAQ (but instead incorporating it all into the UI directly).

Screen Shot 2020-10-06 at 14 11 59

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/329375657)

Updates copy per #275

Adjust copy slightly, assigning @markmhx for review

### CODE REVIEW

File: app/pages/onboarding/05-secret-key/secret-key.tsx [hunk 1]
```diff
@@ -35,8 +35,9 @@ export const SecretKey: React.FC = () => {
     <Onboarding>
       <OnboardingTitle>Your Secret Key</OnboardingTitle>
       <OnboardingText>
-        Here’s your Secret Key: 24 words that prove it’s you when you want to access your wallet.
-        Once lost, it’s lost forever, so save it somewhere you won’t forget.
+        Here's your Secret Key: 24 words that give you access to your Stacks wallet. If you do not
```
Comment (markmhx) [inline app/pages/onboarding/05-secret-key/secret-key.tsx:38]: "Stacks Wallet" with uppercase letters for consistency / branding.

Comment (markmhx) [reply app/pages/onboarding/05-secret-key/secret-key.tsx:38]: And "If you _don't_" for consistency in contractions usage here.

Comment (markmhx) [reply app/pages/onboarding/05-secret-key/secret-key.tsx:38]: Although "If you lose your Secret Key..." may be a better phrasing in any case

**Review by markmhx — CHANGES_REQUESTED** [review]
Small copy changes requested

**Review by markmhx — APPROVED** [review]
