### PR TITLE
fix: various improvements

### LINKED ISSUE #339: Improve Stacking-related copy
All copy related to BTC earning should be framed more in terms of potential rather than promise, and Stacking as a term should be used where helpful.

The following should say "Earn Bitcoin rewards with Stacking" and "You can earn Bitcoin upon temporarily by locking N STX or more":

Screen Shot 2020-11-13 at 13 48 10

We may also want to place a "How Stacking works" link here below the button for those who aren't familiar already, similar to what we have on the Stacking page itself.

The following should say "When you lock your STX, you'll have a chance to earn Bitcoin every week."

Screen Shot 2020-11-13 at 09 05 16
"Lock your STX for chance to earn Bitcoin when the next cycle starts":

Screen Shot 2020-11-13 at 14 00 23

"you'll have the chance to earn Bitcoin":

Screen Shot 2020-11-13 at 13 56 44

"You may receive Bitcoin twice":

Screen Shot 2020-11-13 at 13 57 44

(Although "twice" – is that a constant? why twice?)

### LINKED ISSUE #341: Set number of cycles to maximum by default for Stacking
To encourage longer-term Stacking and reduce the hassle of having to come back and re-Stack:

image

### LINKED ISSUE #348: Normalize the language on transaction execution screens
[](https://mrkr.io/s/5faef39ebdccb41a9164aeaf/0)

All of these should be the same

---

**Reported by:** Bobby (jeff.domke@gmail.com)
**Source URL:** [file:///Users/jd/Desktop/Screen%20Shot%202020-11-13%20at%203.25.20%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202020-11-13%20at%203.25.20%20PM.png)
<table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>Screen Size</strong></td><td>3360 x 1890</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1944 x 1161</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

### LINKED ISSUE #352: Sending: `Sign transaction and send` CTA
Find that language strange for a token send action. Would just say `Confirm` or `Send`

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest builds [4.0.0-beta.7]](https://github.com/blockstack/stacks-wallet/actions/runs/368312869).

Closes #339
Closes #341 
Closes #348
Closes #352

image

### CODE REVIEW

File: app/components/home/stacking-promo-card.tsx [hunk 1]
```diff
@@ -19,10 +19,10 @@ export const StackingPromoCard: FC<StackingPromoCardProps> = ({ minRequiredStx }
     <Flex flexDirection="column" mt="40px" mb="extra-loose">
       <img src={btcPodium} />
       <Text display="block" textAlign="center" textStyle="display.small" mt="loose">
-        Earn Bitcoin rewards
+        Earn Bitcoin rewards with Stacking
       </Text>
       <Text display="block" mt="tight" textAlign="center" maxWidth="320px" mx="auto">
-        You’ll earn Bitcoin when you temporarily lock {Math.ceil(minRequiredStx)} STX or more
+        You can earn Bitcoin upon temporarily by locking {Math.ceil(minRequiredStx)} STX or more
```
Comment (markmhx) [inline app/components/home/stacking-promo-card.tsx:25]: "You can earn Bitcoin by temporarily locking..."

(Note the the current incompatibility between "upon" and "by")

File: app/modals/stacking/stacking-modal.tsx [hunk 2]
```diff
@@ -267,7 +267,7 @@ export const StackingModal: FC<StackingModalProps> = ({ onClose, numCycles, poxA
             isDisabled={isDecrypting}
             onClick={() => broadcastTx()}
           >
-            Send transaction
+            Lock STX
```
Comment (markmhx) [inline app/modals/stacking/stacking-modal.tsx:270]: Should we perhaps say "Initiate Stacking" since we'll say "Initiating Stacking..." soon after in the activity?

File: app/modals/stacking/steps/decrypt-wallet-form.tsx [hunk 3]
```diff
@@ -22,7 +22,9 @@ export const DecryptWalletForm: Props = props => {
   };
   return (
     <Box mx="extra-loose" mt="extra-loose">
-      <Text textStyle="body.large">Enter your password to confirm your transaction</Text>
+      <Text textStyle="body.large">
+        Enter your password to confirm your stacking participation.
```
Comment (markmhx) [inline app/modals/stacking/steps/decrypt-wallet-form.tsx:26]: "Enter your password to initiate Stacking"

**Review by markmhx — CHANGES_REQUESTED** [review]

File: app/components/home/stacking-promo-card.tsx [hunk 4]
```diff
@@ -19,10 +19,10 @@ export const StackingPromoCard: FC<StackingPromoCardProps> = ({ minRequiredStx }
     <Flex flexDirection="column" mt="40px" mb="extra-loose">
       <img src={btcPodium} />
       <Text display="block" textAlign="center" textStyle="display.small" mt="loose">
-        Earn Bitcoin rewards
+        Earn Bitcoin rewards with Stacking
       </Text>
       <Text display="block" mt="tight" textAlign="center" maxWidth="320px" mx="auto">
-        You’ll earn Bitcoin when you temporarily lock {Math.ceil(minRequiredStx)} STX or more
+        You can earn Bitcoin by temporarily locking locking {Math.ceil(minRequiredStx)} STX or more
```
Comment (markmhx) [inline app/components/home/stacking-promo-card.tsx:25]: "locking locking"

**Review by markmhx — CHANGES_REQUESTED** [review]
Just one typo that needs rectifying, otherwise good to 🚢
