### PR TITLE
fix: add memo warning to prevent user error, closes #571

### LINKED ISSUE #571: Add guidance about memos to send and receive modals
It appears that a significant number of users attempting to send STX to exchanges that require transaction memos are failing to include such memos and finding their delivered STX in a sort of purgatory on those exchanges. They then have to follow up with the exchanges' customer support in an attempt to iron it out, though they initially start off confused and concerned that something has gone wrong with the Stacks Wallet itself.

We could perhaps help prevent this situation by adding a note here about the necessity of memos for certain types of transactions:

> ⚠️ Some transactions (such as to exchanges) require a properly formed memo to get processed successfully. [Learn more](http://hiro.so/questions/what-is-the-purpose-of-a-memo)

This note could combine the needs of https://github.com/blockstack/stacks-wallet/issues/490 to say:

> ⚠️ This value will get published to the Stacks blockchain publicly. Some transactions (such as to exchanges) require a properly formed memo to get processed successfully. [Learn more](http://hiro.so/questions/what-is-the-purpose-of-a-memo)

cc @agraebe  @GinaAbrams @ryanarndtcm

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/871058139)

I've seen many reports of this lately so thought it worth trying to work in a fix.

An explicit confirmation when **no memo is needed** seems to be the most common pattern when withdrawing/depositing memo-using currencies, STX, XLM etc. I haven't given much thought to the exact messaging, so please leave feedback.

Closes #571 

https://user-images.githubusercontent.com/1618764/118469334-e6cf5900-b705-11eb-8c7e-6bac4e84e4b1.mp4

### CODE REVIEW

**Comment by markmhx** [comment]
I'll leave this to @jasperjansz to review the design approach.

File: app/modals/send-stx/steps/transaction-form.tsx [hunk 1]
```diff
@@ -82,21 +83,29 @@ export const TxModalForm: FC<TxModalFormProps> = props => {
...
+            textStyle="body.small.medium"
+            mt="base-loose"
+            mr="extra-tight"
+            as="label"
+            {...{ htmlFor: 'stxAmount' }}
+          >
+            Memo
+          </Text>
+          <ExplainerTooltip>
+            Many exchanges require a memo when receiving deposits, in order to credit the customer's
```
Comment (fbwoolf) [inline app/modals/send-stx/steps/transaction-form.tsx:97]: I am not sure a `,` is needed in this sentence?

**Review by fbwoolf — APPROVED** [review]

**Review by jasperjansz — APPROVED** [review]

**Comment by jasperjansz** [comment]
I had explored some different ways. It makes more sense to me to have the toggle above the field, but I defer to mark whether or not that's a change worth making now. https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-%F0%9F%92%BF-desktop?node-id=5460%3A41447.

**Comment by markmhx** [comment]
@kyranjamie let's do this according to @jasperjansz's design spec?

**Comment by kyranjamie** [comment]
Updated in jasper's designs in 12ea257
